// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: structures.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ManageAction int32

const (
	ManageAction_START   ManageAction = 0
	ManageAction_STOP    ManageAction = 1
	ManageAction_STATUS  ManageAction = 2
	ManageAction_RESTART ManageAction = 3
)

// Enum value maps for ManageAction.
var (
	ManageAction_name = map[int32]string{
		0: "START",
		1: "STOP",
		2: "STATUS",
		3: "RESTART",
	}
	ManageAction_value = map[string]int32{
		"START":   0,
		"STOP":    1,
		"STATUS":  2,
		"RESTART": 3,
	}
)

func (x ManageAction) Enum() *ManageAction {
	p := new(ManageAction)
	*p = x
	return p
}

func (x ManageAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ManageAction) Descriptor() protoreflect.EnumDescriptor {
	return file_structures_proto_enumTypes[0].Descriptor()
}

func (ManageAction) Type() protoreflect.EnumType {
	return &file_structures_proto_enumTypes[0]
}

func (x ManageAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ManageAction.Descriptor instead.
func (ManageAction) EnumDescriptor() ([]byte, []int) {
	return file_structures_proto_rawDescGZIP(), []int{0}
}

type InterfaceInfo_State int32

const (
	InterfaceInfo_UP      InterfaceInfo_State = 0
	InterfaceInfo_DOWN    InterfaceInfo_State = 1
	InterfaceInfo_UNKNOWN InterfaceInfo_State = 2
)

// Enum value maps for InterfaceInfo_State.
var (
	InterfaceInfo_State_name = map[int32]string{
		0: "UP",
		1: "DOWN",
		2: "UNKNOWN",
	}
	InterfaceInfo_State_value = map[string]int32{
		"UP":      0,
		"DOWN":    1,
		"UNKNOWN": 2,
	}
)

func (x InterfaceInfo_State) Enum() *InterfaceInfo_State {
	p := new(InterfaceInfo_State)
	*p = x
	return p
}

func (x InterfaceInfo_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InterfaceInfo_State) Descriptor() protoreflect.EnumDescriptor {
	return file_structures_proto_enumTypes[1].Descriptor()
}

func (InterfaceInfo_State) Type() protoreflect.EnumType {
	return &file_structures_proto_enumTypes[1]
}

func (x InterfaceInfo_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InterfaceInfo_State.Descriptor instead.
func (InterfaceInfo_State) EnumDescriptor() ([]byte, []int) {
	return file_structures_proto_rawDescGZIP(), []int{1, 0}
}

type UnblockInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeName      string                 `protobuf:"bytes,1,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	ChainName     string                 `protobuf:"bytes,2,opt,name=chain_name,json=chainName,proto3" json:"chain_name,omitempty"`
	Rules         []string               `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockInfo) Reset() {
	*x = UnblockInfo{}
	mi := &file_structures_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockInfo) ProtoMessage() {}

func (x *UnblockInfo) ProtoReflect() protoreflect.Message {
	mi := &file_structures_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockInfo.ProtoReflect.Descriptor instead.
func (*UnblockInfo) Descriptor() ([]byte, []int) {
	return file_structures_proto_rawDescGZIP(), []int{0}
}

func (x *UnblockInfo) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *UnblockInfo) GetChainName() string {
	if x != nil {
		return x.ChainName
	}
	return ""
}

func (x *UnblockInfo) GetRules() []string {
	if x != nil {
		return x.Rules
	}
	return nil
}

type InterfaceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        InterfaceInfo_State    `protobuf:"varint,4,opt,name=status,proto3,enum=structures.InterfaceInfo_State" json:"status,omitempty"`
	Added         bool                   `protobuf:"varint,5,opt,name=added,proto3" json:"added,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfaceInfo) Reset() {
	*x = InterfaceInfo{}
	mi := &file_structures_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceInfo) ProtoMessage() {}

func (x *InterfaceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_structures_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceInfo.ProtoReflect.Descriptor instead.
func (*InterfaceInfo) Descriptor() ([]byte, []int) {
	return file_structures_proto_rawDescGZIP(), []int{1}
}

func (x *InterfaceInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InterfaceInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InterfaceInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InterfaceInfo) GetStatus() InterfaceInfo_State {
	if x != nil {
		return x.Status
	}
	return InterfaceInfo_UP
}

func (x *InterfaceInfo) GetAdded() bool {
	if x != nil {
		return x.Added
	}
	return false
}

type XrayInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainName     string                 `protobuf:"bytes,1,opt,name=chain_name,json=chainName,proto3" json:"chain_name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Host          string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Status        bool                   `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	AutoRun       bool                   `protobuf:"varint,6,opt,name=auto_run,json=autoRun,proto3" json:"auto_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XrayInfo) Reset() {
	*x = XrayInfo{}
	mi := &file_structures_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XrayInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XrayInfo) ProtoMessage() {}

func (x *XrayInfo) ProtoReflect() protoreflect.Message {
	mi := &file_structures_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XrayInfo.ProtoReflect.Descriptor instead.
func (*XrayInfo) Descriptor() ([]byte, []int) {
	return file_structures_proto_rawDescGZIP(), []int{2}
}

func (x *XrayInfo) GetChainName() string {
	if x != nil {
		return x.ChainName
	}
	return ""
}

func (x *XrayInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *XrayInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *XrayInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *XrayInfo) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *XrayInfo) GetAutoRun() bool {
	if x != nil {
		return x.AutoRun
	}
	return false
}

var File_structures_proto protoreflect.FileDescriptor

const file_structures_proto_rawDesc = "" +
	"\n" +
	"\x10structures.proto\x12\n" +
	"structures\"_\n" +
	"\vUnblockInfo\x12\x1b\n" +
	"\ttype_name\x18\x01 \x01(\tR\btypeName\x12\x1d\n" +
	"\n" +
	"chain_name\x18\x02 \x01(\tR\tchainName\x12\x14\n" +
	"\x05rules\x18\x03 \x03(\tR\x05rules\"\xcc\x01\n" +
	"\rInterfaceInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x127\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1f.structures.InterfaceInfo.StateR\x06status\x12\x14\n" +
	"\x05added\x18\x05 \x01(\bR\x05added\"&\n" +
	"\x05State\x12\x06\n" +
	"\x02UP\x10\x00\x12\b\n" +
	"\x04DOWN\x10\x01\x12\v\n" +
	"\aUNKNOWN\x10\x02\"\x98\x01\n" +
	"\bXrayInfo\x12\x1d\n" +
	"\n" +
	"chain_name\x18\x01 \x01(\tR\tchainName\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x16\n" +
	"\x06status\x18\x05 \x01(\bR\x06status\x12\x19\n" +
	"\bauto_run\x18\x06 \x01(\bR\aautoRun*<\n" +
	"\fManageAction\x12\t\n" +
	"\x05START\x10\x00\x12\b\n" +
	"\x04STOP\x10\x01\x12\n" +
	"\n" +
	"\x06STATUS\x10\x02\x12\v\n" +
	"\aRESTART\x10\x03B,Z*github.com/ApostolDmitry/vpner/proto;protob\x06proto3"

var (
	file_structures_proto_rawDescOnce sync.Once
	file_structures_proto_rawDescData []byte
)

func file_structures_proto_rawDescGZIP() []byte {
	file_structures_proto_rawDescOnce.Do(func() {
		file_structures_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_structures_proto_rawDesc), len(file_structures_proto_rawDesc)))
	})
	return file_structures_proto_rawDescData
}

var file_structures_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_structures_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_structures_proto_goTypes = []any{
	(ManageAction)(0),        // 0: structures.ManageAction
	(InterfaceInfo_State)(0), // 1: structures.InterfaceInfo.State
	(*UnblockInfo)(nil),      // 2: structures.UnblockInfo
	(*InterfaceInfo)(nil),    // 3: structures.InterfaceInfo
	(*XrayInfo)(nil),         // 4: structures.XrayInfo
}
var file_structures_proto_depIdxs = []int32{
	1, // 0: structures.InterfaceInfo.status:type_name -> structures.InterfaceInfo.State
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_structures_proto_init() }
func file_structures_proto_init() {
	if File_structures_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_structures_proto_rawDesc), len(file_structures_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_structures_proto_goTypes,
		DependencyIndexes: file_structures_proto_depIdxs,
		EnumInfos:         file_structures_proto_enumTypes,
		MessageInfos:      file_structures_proto_msgTypes,
	}.Build()
	File_structures_proto = out.File
	file_structures_proto_goTypes = nil
	file_structures_proto_depIdxs = nil
}
