// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: structures.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VpnInfoState int32

const (
	VpnInfo_UP   VpnInfoState = 0
	VpnInfo_DOWN VpnInfoState = 1
)

// Enum value maps for VpnInfoState.
var (
	VpnInfoState_name = map[int32]string{
		0: "UP",
		1: "DOWN",
	}
	VpnInfoState_value = map[string]int32{
		"UP":   0,
		"DOWN": 1,
	}
)

func (x VpnInfoState) Enum() *VpnInfoState {
	p := new(VpnInfoState)
	*p = x
	return p
}

func (x VpnInfoState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VpnInfoState) Descriptor() protoreflect.EnumDescriptor {
	return file_structures_proto_enumTypes[0].Descriptor()
}

func (VpnInfoState) Type() protoreflect.EnumType {
	return &file_structures_proto_enumTypes[0]
}

func (x VpnInfoState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VpnInfoState.Descriptor instead.
func (VpnInfoState) EnumDescriptor() ([]byte, []int) {
	return file_structures_proto_rawDescGZIP(), []int{1, 0}
}

type UnblockInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeName      string                 `protobuf:"bytes,1,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	ChainName     string                 `protobuf:"bytes,2,opt,name=chain_name,json=chainName,proto3" json:"chain_name,omitempty"`
	Rules         []string               `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockInfo) Reset() {
	*x = UnblockInfo{}
	mi := &file_structures_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockInfo) ProtoMessage() {}

func (x *UnblockInfo) ProtoReflect() protoreflect.Message {
	mi := &file_structures_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockInfo.ProtoReflect.Descriptor instead.
func (*UnblockInfo) Descriptor() ([]byte, []int) {
	return file_structures_proto_rawDescGZIP(), []int{0}
}

func (x *UnblockInfo) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *UnblockInfo) GetChainName() string {
	if x != nil {
		return x.ChainName
	}
	return ""
}

func (x *UnblockInfo) GetRules() []string {
	if x != nil {
		return x.Rules
	}
	return nil
}

type VpnInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VpnInfo) Reset() {
	*x = VpnInfo{}
	mi := &file_structures_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VpnInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VpnInfo) ProtoMessage() {}

func (x *VpnInfo) ProtoReflect() protoreflect.Message {
	mi := &file_structures_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VpnInfo.ProtoReflect.Descriptor instead.
func (*VpnInfo) Descriptor() ([]byte, []int) {
	return file_structures_proto_rawDescGZIP(), []int{1}
}

func (x *VpnInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VpnInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *VpnInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_structures_proto protoreflect.FileDescriptor

const file_structures_proto_rawDesc = "" +
	"\n" +
	"\x10structures.proto\x12\n" +
	"structures\"_\n" +
	"\vUnblockInfo\x12\x1b\n" +
	"\ttype_name\x18\x01 \x01(\tR\btypeName\x12\x1d\n" +
	"\n" +
	"chain_name\x18\x02 \x01(\tR\tchainName\x12\x14\n" +
	"\x05rules\x18\x03 \x03(\tR\x05rules\"j\n" +
	"\aVpnInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x19\n" +
	"\x05state\x12\x06\n" +
	"\x02UP\x10\x00\x12\b\n" +
	"\x04DOWN\x10\x01B,Z*github.com/ApostolDmitry/vpner/proto;protob\x06proto3"

var (
	file_structures_proto_rawDescOnce sync.Once
	file_structures_proto_rawDescData []byte
)

func file_structures_proto_rawDescGZIP() []byte {
	file_structures_proto_rawDescOnce.Do(func() {
		file_structures_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_structures_proto_rawDesc), len(file_structures_proto_rawDesc)))
	})
	return file_structures_proto_rawDescData
}

var file_structures_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_structures_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_structures_proto_goTypes = []any{
	(VpnInfoState)(0),   // 0: structures.VpnInfo.state
	(*UnblockInfo)(nil), // 1: structures.UnblockInfo
	(*VpnInfo)(nil),     // 2: structures.VpnInfo
}
var file_structures_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_structures_proto_init() }
func file_structures_proto_init() {
	if File_structures_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_structures_proto_rawDesc), len(file_structures_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_structures_proto_goTypes,
		DependencyIndexes: file_structures_proto_depIdxs,
		EnumInfos:         file_structures_proto_enumTypes,
		MessageInfos:      file_structures_proto_msgTypes,
	}.Build()
	File_structures_proto = out.File
	file_structures_proto_goTypes = nil
	file_structures_proto_depIdxs = nil
}
