// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: vpner.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DnsManageResponseAction int32

const (
	DnsManageResponse_START   DnsManageResponseAction = 0
	DnsManageResponse_STOP    DnsManageResponseAction = 1
	DnsManageResponse_STATUS  DnsManageResponseAction = 3
	DnsManageResponse_RESTART DnsManageResponseAction = 4
)

// Enum value maps for DnsManageResponseAction.
var (
	DnsManageResponseAction_name = map[int32]string{
		0: "START",
		1: "STOP",
		3: "STATUS",
		4: "RESTART",
	}
	DnsManageResponseAction_value = map[string]int32{
		"START":   0,
		"STOP":    1,
		"STATUS":  3,
		"RESTART": 4,
	}
)

func (x DnsManageResponseAction) Enum() *DnsManageResponseAction {
	p := new(DnsManageResponseAction)
	*p = x
	return p
}

func (x DnsManageResponseAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DnsManageResponseAction) Descriptor() protoreflect.EnumDescriptor {
	return file_vpner_proto_enumTypes[0].Descriptor()
}

func (DnsManageResponseAction) Type() protoreflect.EnumType {
	return &file_vpner_proto_enumTypes[0]
}

func (x DnsManageResponseAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DnsManageResponseAction.Descriptor instead.
func (DnsManageResponseAction) EnumDescriptor() ([]byte, []int) {
	return file_vpner_proto_rawDescGZIP(), []int{12, 0}
}

type Success struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Success) Reset() {
	*x = Success{}
	mi := &file_vpner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Success) ProtoMessage() {}

func (x *Success) ProtoReflect() protoreflect.Message {
	mi := &file_vpner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Success.ProtoReflect.Descriptor instead.
func (*Success) Descriptor() ([]byte, []int) {
	return file_vpner_proto_rawDescGZIP(), []int{0}
}

func (x *Success) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_vpner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_vpner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_vpner_proto_rawDescGZIP(), []int{1}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnblockListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockListResponse) Reset() {
	*x = UnblockListResponse{}
	mi := &file_vpner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockListResponse) ProtoMessage() {}

func (x *UnblockListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vpner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockListResponse.ProtoReflect.Descriptor instead.
func (*UnblockListResponse) Descriptor() ([]byte, []int) {
	return file_vpner_proto_rawDescGZIP(), []int{2}
}

type UnblockListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*UnblockInfo         `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockListRequest) Reset() {
	*x = UnblockListRequest{}
	mi := &file_vpner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockListRequest) ProtoMessage() {}

func (x *UnblockListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vpner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockListRequest.ProtoReflect.Descriptor instead.
func (*UnblockListRequest) Descriptor() ([]byte, []int) {
	return file_vpner_proto_rawDescGZIP(), []int{3}
}

func (x *UnblockListRequest) GetRules() []*UnblockInfo {
	if x != nil {
		return x.Rules
	}
	return nil
}

type UnblockAddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	ChainName     string                 `protobuf:"bytes,2,opt,name=chain_name,json=chainName,proto3" json:"chain_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockAddResponse) Reset() {
	*x = UnblockAddResponse{}
	mi := &file_vpner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockAddResponse) ProtoMessage() {}

func (x *UnblockAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vpner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockAddResponse.ProtoReflect.Descriptor instead.
func (*UnblockAddResponse) Descriptor() ([]byte, []int) {
	return file_vpner_proto_rawDescGZIP(), []int{4}
}

func (x *UnblockAddResponse) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *UnblockAddResponse) GetChainName() string {
	if x != nil {
		return x.ChainName
	}
	return ""
}

type UnblockAddRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*UnblockAddRequest_Success
	//	*UnblockAddRequest_Error
	Result        isUnblockAddRequest_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockAddRequest) Reset() {
	*x = UnblockAddRequest{}
	mi := &file_vpner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockAddRequest) ProtoMessage() {}

func (x *UnblockAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vpner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockAddRequest.ProtoReflect.Descriptor instead.
func (*UnblockAddRequest) Descriptor() ([]byte, []int) {
	return file_vpner_proto_rawDescGZIP(), []int{5}
}

func (x *UnblockAddRequest) GetResult() isUnblockAddRequest_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *UnblockAddRequest) GetSuccess() *Success {
	if x != nil {
		if x, ok := x.Result.(*UnblockAddRequest_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *UnblockAddRequest) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*UnblockAddRequest_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isUnblockAddRequest_Result interface {
	isUnblockAddRequest_Result()
}

type UnblockAddRequest_Success struct {
	Success *Success `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type UnblockAddRequest_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*UnblockAddRequest_Success) isUnblockAddRequest_Result() {}

func (*UnblockAddRequest_Error) isUnblockAddRequest_Result() {}

type UnblockDelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	ChainName     string                 `protobuf:"bytes,2,opt,name=chain_name,json=chainName,proto3" json:"chain_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockDelResponse) Reset() {
	*x = UnblockDelResponse{}
	mi := &file_vpner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockDelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockDelResponse) ProtoMessage() {}

func (x *UnblockDelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vpner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockDelResponse.ProtoReflect.Descriptor instead.
func (*UnblockDelResponse) Descriptor() ([]byte, []int) {
	return file_vpner_proto_rawDescGZIP(), []int{6}
}

func (x *UnblockDelResponse) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *UnblockDelResponse) GetChainName() string {
	if x != nil {
		return x.ChainName
	}
	return ""
}

type UnblockDelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*UnblockDelRequest_Success
	//	*UnblockDelRequest_Error
	Result        isUnblockDelRequest_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockDelRequest) Reset() {
	*x = UnblockDelRequest{}
	mi := &file_vpner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockDelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockDelRequest) ProtoMessage() {}

func (x *UnblockDelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vpner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockDelRequest.ProtoReflect.Descriptor instead.
func (*UnblockDelRequest) Descriptor() ([]byte, []int) {
	return file_vpner_proto_rawDescGZIP(), []int{7}
}

func (x *UnblockDelRequest) GetResult() isUnblockDelRequest_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *UnblockDelRequest) GetSuccess() *Success {
	if x != nil {
		if x, ok := x.Result.(*UnblockDelRequest_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *UnblockDelRequest) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*UnblockDelRequest_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isUnblockDelRequest_Result interface {
	isUnblockDelRequest_Result()
}

type UnblockDelRequest_Success struct {
	Success *Success `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type UnblockDelRequest_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*UnblockDelRequest_Success) isUnblockDelRequest_Result() {}

func (*UnblockDelRequest_Error) isUnblockDelRequest_Result() {}

type VpnListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VpnListResponse) Reset() {
	*x = VpnListResponse{}
	mi := &file_vpner_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VpnListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VpnListResponse) ProtoMessage() {}

func (x *VpnListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vpner_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VpnListResponse.ProtoReflect.Descriptor instead.
func (*VpnListResponse) Descriptor() ([]byte, []int) {
	return file_vpner_proto_rawDescGZIP(), []int{8}
}

type VpnListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interfaces    []*VpnInfo             `protobuf:"bytes,1,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VpnListRequest) Reset() {
	*x = VpnListRequest{}
	mi := &file_vpner_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VpnListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VpnListRequest) ProtoMessage() {}

func (x *VpnListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vpner_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VpnListRequest.ProtoReflect.Descriptor instead.
func (*VpnListRequest) Descriptor() ([]byte, []int) {
	return file_vpner_proto_rawDescGZIP(), []int{9}
}

func (x *VpnListRequest) GetInterfaces() []*VpnInfo {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

type VpnSelectionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SelectedInterface int32                  `protobuf:"varint,1,opt,name=selected_interface,json=selectedInterface,proto3" json:"selected_interface,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VpnSelectionResponse) Reset() {
	*x = VpnSelectionResponse{}
	mi := &file_vpner_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VpnSelectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VpnSelectionResponse) ProtoMessage() {}

func (x *VpnSelectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vpner_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VpnSelectionResponse.ProtoReflect.Descriptor instead.
func (*VpnSelectionResponse) Descriptor() ([]byte, []int) {
	return file_vpner_proto_rawDescGZIP(), []int{10}
}

func (x *VpnSelectionResponse) GetSelectedInterface() int32 {
	if x != nil {
		return x.SelectedInterface
	}
	return 0
}

type VpnScanMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*VpnScanMessage_List
	//	*VpnScanMessage_Select
	//	*VpnScanMessage_Error
	Payload       isVpnScanMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VpnScanMessage) Reset() {
	*x = VpnScanMessage{}
	mi := &file_vpner_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VpnScanMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VpnScanMessage) ProtoMessage() {}

func (x *VpnScanMessage) ProtoReflect() protoreflect.Message {
	mi := &file_vpner_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VpnScanMessage.ProtoReflect.Descriptor instead.
func (*VpnScanMessage) Descriptor() ([]byte, []int) {
	return file_vpner_proto_rawDescGZIP(), []int{11}
}

func (x *VpnScanMessage) GetPayload() isVpnScanMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *VpnScanMessage) GetList() *VpnListResponse {
	if x != nil {
		if x, ok := x.Payload.(*VpnScanMessage_List); ok {
			return x.List
		}
	}
	return nil
}

func (x *VpnScanMessage) GetSelect() *VpnSelectionResponse {
	if x != nil {
		if x, ok := x.Payload.(*VpnScanMessage_Select); ok {
			return x.Select
		}
	}
	return nil
}

func (x *VpnScanMessage) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*VpnScanMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isVpnScanMessage_Payload interface {
	isVpnScanMessage_Payload()
}

type VpnScanMessage_List struct {
	List *VpnListResponse `protobuf:"bytes,1,opt,name=list,proto3,oneof"`
}

type VpnScanMessage_Select struct {
	Select *VpnSelectionResponse `protobuf:"bytes,2,opt,name=select,proto3,oneof"`
}

type VpnScanMessage_Error struct {
	Error *Error `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*VpnScanMessage_List) isVpnScanMessage_Payload() {}

func (*VpnScanMessage_Select) isVpnScanMessage_Payload() {}

func (*VpnScanMessage_Error) isVpnScanMessage_Payload() {}

type DnsManageResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Act           DnsManageResponseAction `protobuf:"varint,1,opt,name=act,proto3,enum=vpner.DnsManageResponseAction" json:"act,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DnsManageResponse) Reset() {
	*x = DnsManageResponse{}
	mi := &file_vpner_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DnsManageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DnsManageResponse) ProtoMessage() {}

func (x *DnsManageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vpner_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DnsManageResponse.ProtoReflect.Descriptor instead.
func (*DnsManageResponse) Descriptor() ([]byte, []int) {
	return file_vpner_proto_rawDescGZIP(), []int{12}
}

func (x *DnsManageResponse) GetAct() DnsManageResponseAction {
	if x != nil {
		return x.Act
	}
	return DnsManageResponse_START
}

type DnsManageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*DnsManageRequest_Success
	//	*DnsManageRequest_Error
	Result        isDnsManageRequest_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DnsManageRequest) Reset() {
	*x = DnsManageRequest{}
	mi := &file_vpner_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DnsManageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DnsManageRequest) ProtoMessage() {}

func (x *DnsManageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vpner_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DnsManageRequest.ProtoReflect.Descriptor instead.
func (*DnsManageRequest) Descriptor() ([]byte, []int) {
	return file_vpner_proto_rawDescGZIP(), []int{13}
}

func (x *DnsManageRequest) GetResult() isDnsManageRequest_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *DnsManageRequest) GetSuccess() *Success {
	if x != nil {
		if x, ok := x.Result.(*DnsManageRequest_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *DnsManageRequest) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*DnsManageRequest_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isDnsManageRequest_Result interface {
	isDnsManageRequest_Result()
}

type DnsManageRequest_Success struct {
	Success *Success `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type DnsManageRequest_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*DnsManageRequest_Success) isDnsManageRequest_Result() {}

func (*DnsManageRequest_Error) isDnsManageRequest_Result() {}

var File_vpner_proto protoreflect.FileDescriptor

const file_vpner_proto_rawDesc = "" +
	"\n" +
	"\vvpner.proto\x12\x05vpner\x1a\x10structures.proto\"#\n" +
	"\aSuccess\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"!\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x15\n" +
	"\x13UnblockListResponse\"C\n" +
	"\x12UnblockListRequest\x12-\n" +
	"\x05rules\x18\x01 \x03(\v2\x17.structures.UnblockInfoR\x05rules\"K\n" +
	"\x12UnblockAddResponse\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x1d\n" +
	"\n" +
	"chain_name\x18\x02 \x01(\tR\tchainName\"o\n" +
	"\x11UnblockAddRequest\x12*\n" +
	"\asuccess\x18\x01 \x01(\v2\x0e.vpner.SuccessH\x00R\asuccess\x12$\n" +
	"\x05error\x18\x02 \x01(\v2\f.vpner.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\"K\n" +
	"\x12UnblockDelResponse\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x1d\n" +
	"\n" +
	"chain_name\x18\x02 \x01(\tR\tchainName\"o\n" +
	"\x11UnblockDelRequest\x12*\n" +
	"\asuccess\x18\x01 \x01(\v2\x0e.vpner.SuccessH\x00R\asuccess\x12$\n" +
	"\x05error\x18\x02 \x01(\v2\f.vpner.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\"\x11\n" +
	"\x0fVpnListResponse\"E\n" +
	"\x0eVpnListRequest\x123\n" +
	"\n" +
	"interfaces\x18\x01 \x03(\v2\x13.structures.VpnInfoR\n" +
	"interfaces\"E\n" +
	"\x14VpnSelectionResponse\x12-\n" +
	"\x12selected_interface\x18\x01 \x01(\x05R\x11selectedInterface\"\xa6\x01\n" +
	"\x0eVpnScanMessage\x12,\n" +
	"\x04list\x18\x01 \x01(\v2\x16.vpner.VpnListResponseH\x00R\x04list\x125\n" +
	"\x06select\x18\x02 \x01(\v2\x1b.vpner.VpnSelectionResponseH\x00R\x06select\x12$\n" +
	"\x05error\x18\x03 \x01(\v2\f.vpner.ErrorH\x00R\x05errorB\t\n" +
	"\apayload\"~\n" +
	"\x11DnsManageResponse\x121\n" +
	"\x03act\x18\x01 \x01(\x0e2\x1f.vpner.DnsManageResponse.actionR\x03act\"6\n" +
	"\x06action\x12\t\n" +
	"\x05START\x10\x00\x12\b\n" +
	"\x04STOP\x10\x01\x12\n" +
	"\n" +
	"\x06STATUS\x10\x03\x12\v\n" +
	"\aRESTART\x10\x04\"n\n" +
	"\x10DnsManageRequest\x12*\n" +
	"\asuccess\x18\x01 \x01(\v2\x0e.vpner.SuccessH\x00R\asuccess\x12$\n" +
	"\x05error\x18\x02 \x01(\v2\f.vpner.ErrorH\x00R\x05errorB\b\n" +
	"\x06result2\x91\x03\n" +
	"\fVpnerManager\x12D\n" +
	"\vunblockList\x12\x1a.vpner.UnblockListResponse\x1a\x19.vpner.UnblockListRequest\x12A\n" +
	"\n" +
	"unblockAdd\x12\x19.vpner.UnblockAddResponse\x1a\x18.vpner.UnblockAddRequest\x12A\n" +
	"\n" +
	"unblockDel\x12\x19.vpner.UnblockDelResponse\x1a\x18.vpner.UnblockDelRequest\x128\n" +
	"\avpnList\x12\x16.vpner.VpnListResponse\x1a\x15.vpner.VpnListRequest\x12;\n" +
	"\avpnScan\x12\x15.vpner.VpnScanMessage\x1a\x15.vpner.VpnScanMessage(\x010\x01\x12>\n" +
	"\tdnsManage\x12\x18.vpner.DnsManageResponse\x1a\x17.vpner.DnsManageRequestB,Z*github.com/ApostolDmitry/vpner/proto;protob\x06proto3"

var (
	file_vpner_proto_rawDescOnce sync.Once
	file_vpner_proto_rawDescData []byte
)

func file_vpner_proto_rawDescGZIP() []byte {
	file_vpner_proto_rawDescOnce.Do(func() {
		file_vpner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vpner_proto_rawDesc), len(file_vpner_proto_rawDesc)))
	})
	return file_vpner_proto_rawDescData
}

var file_vpner_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vpner_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_vpner_proto_goTypes = []any{
	(DnsManageResponseAction)(0), // 0: vpner.DnsManageResponse.action
	(*Success)(nil),              // 1: vpner.Success
	(*Error)(nil),                // 2: vpner.Error
	(*UnblockListResponse)(nil),  // 3: vpner.UnblockListResponse
	(*UnblockListRequest)(nil),   // 4: vpner.UnblockListRequest
	(*UnblockAddResponse)(nil),   // 5: vpner.UnblockAddResponse
	(*UnblockAddRequest)(nil),    // 6: vpner.UnblockAddRequest
	(*UnblockDelResponse)(nil),   // 7: vpner.UnblockDelResponse
	(*UnblockDelRequest)(nil),    // 8: vpner.UnblockDelRequest
	(*VpnListResponse)(nil),      // 9: vpner.VpnListResponse
	(*VpnListRequest)(nil),       // 10: vpner.VpnListRequest
	(*VpnSelectionResponse)(nil), // 11: vpner.VpnSelectionResponse
	(*VpnScanMessage)(nil),       // 12: vpner.VpnScanMessage
	(*DnsManageResponse)(nil),    // 13: vpner.DnsManageResponse
	(*DnsManageRequest)(nil),     // 14: vpner.DnsManageRequest
	(*UnblockInfo)(nil),          // 15: structures.UnblockInfo
	(*VpnInfo)(nil),              // 16: structures.VpnInfo
}
var file_vpner_proto_depIdxs = []int32{
	15, // 0: vpner.UnblockListRequest.rules:type_name -> structures.UnblockInfo
	1,  // 1: vpner.UnblockAddRequest.success:type_name -> vpner.Success
	2,  // 2: vpner.UnblockAddRequest.error:type_name -> vpner.Error
	1,  // 3: vpner.UnblockDelRequest.success:type_name -> vpner.Success
	2,  // 4: vpner.UnblockDelRequest.error:type_name -> vpner.Error
	16, // 5: vpner.VpnListRequest.interfaces:type_name -> structures.VpnInfo
	9,  // 6: vpner.VpnScanMessage.list:type_name -> vpner.VpnListResponse
	11, // 7: vpner.VpnScanMessage.select:type_name -> vpner.VpnSelectionResponse
	2,  // 8: vpner.VpnScanMessage.error:type_name -> vpner.Error
	0,  // 9: vpner.DnsManageResponse.act:type_name -> vpner.DnsManageResponse.action
	1,  // 10: vpner.DnsManageRequest.success:type_name -> vpner.Success
	2,  // 11: vpner.DnsManageRequest.error:type_name -> vpner.Error
	3,  // 12: vpner.VpnerManager.unblockList:input_type -> vpner.UnblockListResponse
	5,  // 13: vpner.VpnerManager.unblockAdd:input_type -> vpner.UnblockAddResponse
	7,  // 14: vpner.VpnerManager.unblockDel:input_type -> vpner.UnblockDelResponse
	9,  // 15: vpner.VpnerManager.vpnList:input_type -> vpner.VpnListResponse
	12, // 16: vpner.VpnerManager.vpnScan:input_type -> vpner.VpnScanMessage
	13, // 17: vpner.VpnerManager.dnsManage:input_type -> vpner.DnsManageResponse
	4,  // 18: vpner.VpnerManager.unblockList:output_type -> vpner.UnblockListRequest
	6,  // 19: vpner.VpnerManager.unblockAdd:output_type -> vpner.UnblockAddRequest
	8,  // 20: vpner.VpnerManager.unblockDel:output_type -> vpner.UnblockDelRequest
	10, // 21: vpner.VpnerManager.vpnList:output_type -> vpner.VpnListRequest
	12, // 22: vpner.VpnerManager.vpnScan:output_type -> vpner.VpnScanMessage
	14, // 23: vpner.VpnerManager.dnsManage:output_type -> vpner.DnsManageRequest
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_vpner_proto_init() }
func file_vpner_proto_init() {
	if File_vpner_proto != nil {
		return
	}
	file_structures_proto_init()
	file_vpner_proto_msgTypes[5].OneofWrappers = []any{
		(*UnblockAddRequest_Success)(nil),
		(*UnblockAddRequest_Error)(nil),
	}
	file_vpner_proto_msgTypes[7].OneofWrappers = []any{
		(*UnblockDelRequest_Success)(nil),
		(*UnblockDelRequest_Error)(nil),
	}
	file_vpner_proto_msgTypes[11].OneofWrappers = []any{
		(*VpnScanMessage_List)(nil),
		(*VpnScanMessage_Select)(nil),
		(*VpnScanMessage_Error)(nil),
	}
	file_vpner_proto_msgTypes[13].OneofWrappers = []any{
		(*DnsManageRequest_Success)(nil),
		(*DnsManageRequest_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vpner_proto_rawDesc), len(file_vpner_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vpner_proto_goTypes,
		DependencyIndexes: file_vpner_proto_depIdxs,
		EnumInfos:         file_vpner_proto_enumTypes,
		MessageInfos:      file_vpner_proto_msgTypes,
	}.Build()
	File_vpner_proto = out.File
	file_vpner_proto_goTypes = nil
	file_vpner_proto_depIdxs = nil
}
