// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: vpner.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VpnerManager_UnblockList_FullMethodName = "/vpner.VpnerManager/unblockList"
	VpnerManager_UnblockAdd_FullMethodName  = "/vpner.VpnerManager/unblockAdd"
	VpnerManager_UnblockDel_FullMethodName  = "/vpner.VpnerManager/unblockDel"
	VpnerManager_VpnList_FullMethodName     = "/vpner.VpnerManager/vpnList"
	VpnerManager_VpnScan_FullMethodName     = "/vpner.VpnerManager/vpnScan"
	VpnerManager_DnsManage_FullMethodName   = "/vpner.VpnerManager/dnsManage"
)

// VpnerManagerClient is the client API for VpnerManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VpnerManagerClient interface {
	UnblockList(ctx context.Context, in *UnblockListResponse, opts ...grpc.CallOption) (*UnblockListRequest, error)
	UnblockAdd(ctx context.Context, in *UnblockAddResponse, opts ...grpc.CallOption) (*UnblockAddRequest, error)
	UnblockDel(ctx context.Context, in *UnblockDelResponse, opts ...grpc.CallOption) (*UnblockDelRequest, error)
	VpnList(ctx context.Context, in *VpnListResponse, opts ...grpc.CallOption) (*VpnListRequest, error)
	VpnScan(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[VpnScanMessage, VpnScanMessage], error)
	DnsManage(ctx context.Context, in *DnsManageResponse, opts ...grpc.CallOption) (*DnsManageRequest, error)
}

type vpnerManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewVpnerManagerClient(cc grpc.ClientConnInterface) VpnerManagerClient {
	return &vpnerManagerClient{cc}
}

func (c *vpnerManagerClient) UnblockList(ctx context.Context, in *UnblockListResponse, opts ...grpc.CallOption) (*UnblockListRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnblockListRequest)
	err := c.cc.Invoke(ctx, VpnerManager_UnblockList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnerManagerClient) UnblockAdd(ctx context.Context, in *UnblockAddResponse, opts ...grpc.CallOption) (*UnblockAddRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnblockAddRequest)
	err := c.cc.Invoke(ctx, VpnerManager_UnblockAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnerManagerClient) UnblockDel(ctx context.Context, in *UnblockDelResponse, opts ...grpc.CallOption) (*UnblockDelRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnblockDelRequest)
	err := c.cc.Invoke(ctx, VpnerManager_UnblockDel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnerManagerClient) VpnList(ctx context.Context, in *VpnListResponse, opts ...grpc.CallOption) (*VpnListRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VpnListRequest)
	err := c.cc.Invoke(ctx, VpnerManager_VpnList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnerManagerClient) VpnScan(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[VpnScanMessage, VpnScanMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VpnerManager_ServiceDesc.Streams[0], VpnerManager_VpnScan_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[VpnScanMessage, VpnScanMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VpnerManager_VpnScanClient = grpc.BidiStreamingClient[VpnScanMessage, VpnScanMessage]

func (c *vpnerManagerClient) DnsManage(ctx context.Context, in *DnsManageResponse, opts ...grpc.CallOption) (*DnsManageRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DnsManageRequest)
	err := c.cc.Invoke(ctx, VpnerManager_DnsManage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VpnerManagerServer is the server API for VpnerManager service.
// All implementations must embed UnimplementedVpnerManagerServer
// for forward compatibility.
type VpnerManagerServer interface {
	UnblockList(context.Context, *UnblockListResponse) (*UnblockListRequest, error)
	UnblockAdd(context.Context, *UnblockAddResponse) (*UnblockAddRequest, error)
	UnblockDel(context.Context, *UnblockDelResponse) (*UnblockDelRequest, error)
	VpnList(context.Context, *VpnListResponse) (*VpnListRequest, error)
	VpnScan(grpc.BidiStreamingServer[VpnScanMessage, VpnScanMessage]) error
	DnsManage(context.Context, *DnsManageResponse) (*DnsManageRequest, error)
	mustEmbedUnimplementedVpnerManagerServer()
}

// UnimplementedVpnerManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVpnerManagerServer struct{}

func (UnimplementedVpnerManagerServer) UnblockList(context.Context, *UnblockListResponse) (*UnblockListRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnblockList not implemented")
}
func (UnimplementedVpnerManagerServer) UnblockAdd(context.Context, *UnblockAddResponse) (*UnblockAddRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnblockAdd not implemented")
}
func (UnimplementedVpnerManagerServer) UnblockDel(context.Context, *UnblockDelResponse) (*UnblockDelRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnblockDel not implemented")
}
func (UnimplementedVpnerManagerServer) VpnList(context.Context, *VpnListResponse) (*VpnListRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VpnList not implemented")
}
func (UnimplementedVpnerManagerServer) VpnScan(grpc.BidiStreamingServer[VpnScanMessage, VpnScanMessage]) error {
	return status.Errorf(codes.Unimplemented, "method VpnScan not implemented")
}
func (UnimplementedVpnerManagerServer) DnsManage(context.Context, *DnsManageResponse) (*DnsManageRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DnsManage not implemented")
}
func (UnimplementedVpnerManagerServer) mustEmbedUnimplementedVpnerManagerServer() {}
func (UnimplementedVpnerManagerServer) testEmbeddedByValue()                      {}

// UnsafeVpnerManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VpnerManagerServer will
// result in compilation errors.
type UnsafeVpnerManagerServer interface {
	mustEmbedUnimplementedVpnerManagerServer()
}

func RegisterVpnerManagerServer(s grpc.ServiceRegistrar, srv VpnerManagerServer) {
	// If the following call pancis, it indicates UnimplementedVpnerManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VpnerManager_ServiceDesc, srv)
}

func _VpnerManager_UnblockList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnblockListResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnerManagerServer).UnblockList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VpnerManager_UnblockList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnerManagerServer).UnblockList(ctx, req.(*UnblockListResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _VpnerManager_UnblockAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnblockAddResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnerManagerServer).UnblockAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VpnerManager_UnblockAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnerManagerServer).UnblockAdd(ctx, req.(*UnblockAddResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _VpnerManager_UnblockDel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnblockDelResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnerManagerServer).UnblockDel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VpnerManager_UnblockDel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnerManagerServer).UnblockDel(ctx, req.(*UnblockDelResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _VpnerManager_VpnList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VpnListResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnerManagerServer).VpnList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VpnerManager_VpnList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnerManagerServer).VpnList(ctx, req.(*VpnListResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _VpnerManager_VpnScan_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VpnerManagerServer).VpnScan(&grpc.GenericServerStream[VpnScanMessage, VpnScanMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VpnerManager_VpnScanServer = grpc.BidiStreamingServer[VpnScanMessage, VpnScanMessage]

func _VpnerManager_DnsManage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DnsManageResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnerManagerServer).DnsManage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VpnerManager_DnsManage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnerManagerServer).DnsManage(ctx, req.(*DnsManageResponse))
	}
	return interceptor(ctx, in, info, handler)
}

// VpnerManager_ServiceDesc is the grpc.ServiceDesc for VpnerManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VpnerManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vpner.VpnerManager",
	HandlerType: (*VpnerManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "unblockList",
			Handler:    _VpnerManager_UnblockList_Handler,
		},
		{
			MethodName: "unblockAdd",
			Handler:    _VpnerManager_UnblockAdd_Handler,
		},
		{
			MethodName: "unblockDel",
			Handler:    _VpnerManager_UnblockDel_Handler,
		},
		{
			MethodName: "vpnList",
			Handler:    _VpnerManager_VpnList_Handler,
		},
		{
			MethodName: "dnsManage",
			Handler:    _VpnerManager_DnsManage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "vpnScan",
			Handler:       _VpnerManager_VpnScan_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "vpner.proto",
}
