// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: vpner.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VpnerManager_UnblockList_FullMethodName    = "/vpner.VpnerManager/UnblockList"
	VpnerManager_UnblockAdd_FullMethodName     = "/vpner.VpnerManager/UnblockAdd"
	VpnerManager_UnblockDel_FullMethodName     = "/vpner.VpnerManager/UnblockDel"
	VpnerManager_InterfaceList_FullMethodName  = "/vpner.VpnerManager/InterfaceList"
	VpnerManager_InterfaceScan_FullMethodName  = "/vpner.VpnerManager/InterfaceScan"
	VpnerManager_InterfaceAdd_FullMethodName   = "/vpner.VpnerManager/InterfaceAdd"
	VpnerManager_InterfaceDel_FullMethodName   = "/vpner.VpnerManager/InterfaceDel"
	VpnerManager_DnsManage_FullMethodName      = "/vpner.VpnerManager/DnsManage"
	VpnerManager_XrayCreate_FullMethodName     = "/vpner.VpnerManager/XrayCreate"
	VpnerManager_XrayDelete_FullMethodName     = "/vpner.VpnerManager/XrayDelete"
	VpnerManager_XrayList_FullMethodName       = "/vpner.VpnerManager/XrayList"
	VpnerManager_XrayManage_FullMethodName     = "/vpner.VpnerManager/XrayManage"
	VpnerManager_XraySetAutorun_FullMethodName = "/vpner.VpnerManager/XraySetAutorun"
	VpnerManager_HookRestore_FullMethodName    = "/vpner.VpnerManager/HookRestore"
)

// VpnerManagerClient is the client API for VpnerManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VpnerManagerClient interface {
	// Unblock rules
	UnblockList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UnblockListResponse, error)
	UnblockAdd(ctx context.Context, in *UnblockAddRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	UnblockDel(ctx context.Context, in *UnblockDelRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	// Interfaces
	InterfaceList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*InterfaceListResponse, error)
	InterfaceScan(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*InterfaceListResponse, error)
	InterfaceAdd(ctx context.Context, in *InterfaceActionRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	InterfaceDel(ctx context.Context, in *InterfaceActionRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	// DNS management
	DnsManage(ctx context.Context, in *ManageRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	// xray manager
	XrayCreate(ctx context.Context, in *XrayCreateRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	XrayDelete(ctx context.Context, in *XrayRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	XrayList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*XrayListResponse, error)
	XrayManage(ctx context.Context, in *XrayManageRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	XraySetAutorun(ctx context.Context, in *XrayAutoRunRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	HookRestore(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GenericResponse, error)
}

type vpnerManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewVpnerManagerClient(cc grpc.ClientConnInterface) VpnerManagerClient {
	return &vpnerManagerClient{cc}
}

func (c *vpnerManagerClient) UnblockList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UnblockListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnblockListResponse)
	err := c.cc.Invoke(ctx, VpnerManager_UnblockList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnerManagerClient) UnblockAdd(ctx context.Context, in *UnblockAddRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, VpnerManager_UnblockAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnerManagerClient) UnblockDel(ctx context.Context, in *UnblockDelRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, VpnerManager_UnblockDel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnerManagerClient) InterfaceList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*InterfaceListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InterfaceListResponse)
	err := c.cc.Invoke(ctx, VpnerManager_InterfaceList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnerManagerClient) InterfaceScan(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*InterfaceListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InterfaceListResponse)
	err := c.cc.Invoke(ctx, VpnerManager_InterfaceScan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnerManagerClient) InterfaceAdd(ctx context.Context, in *InterfaceActionRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, VpnerManager_InterfaceAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnerManagerClient) InterfaceDel(ctx context.Context, in *InterfaceActionRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, VpnerManager_InterfaceDel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnerManagerClient) DnsManage(ctx context.Context, in *ManageRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, VpnerManager_DnsManage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnerManagerClient) XrayCreate(ctx context.Context, in *XrayCreateRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, VpnerManager_XrayCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnerManagerClient) XrayDelete(ctx context.Context, in *XrayRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, VpnerManager_XrayDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnerManagerClient) XrayList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*XrayListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(XrayListResponse)
	err := c.cc.Invoke(ctx, VpnerManager_XrayList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnerManagerClient) XrayManage(ctx context.Context, in *XrayManageRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, VpnerManager_XrayManage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnerManagerClient) XraySetAutorun(ctx context.Context, in *XrayAutoRunRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, VpnerManager_XraySetAutorun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vpnerManagerClient) HookRestore(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, VpnerManager_HookRestore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VpnerManagerServer is the server API for VpnerManager service.
// All implementations must embed UnimplementedVpnerManagerServer
// for forward compatibility.
type VpnerManagerServer interface {
	// Unblock rules
	UnblockList(context.Context, *Empty) (*UnblockListResponse, error)
	UnblockAdd(context.Context, *UnblockAddRequest) (*GenericResponse, error)
	UnblockDel(context.Context, *UnblockDelRequest) (*GenericResponse, error)
	// Interfaces
	InterfaceList(context.Context, *Empty) (*InterfaceListResponse, error)
	InterfaceScan(context.Context, *Empty) (*InterfaceListResponse, error)
	InterfaceAdd(context.Context, *InterfaceActionRequest) (*GenericResponse, error)
	InterfaceDel(context.Context, *InterfaceActionRequest) (*GenericResponse, error)
	// DNS management
	DnsManage(context.Context, *ManageRequest) (*GenericResponse, error)
	// xray manager
	XrayCreate(context.Context, *XrayCreateRequest) (*GenericResponse, error)
	XrayDelete(context.Context, *XrayRequest) (*GenericResponse, error)
	XrayList(context.Context, *Empty) (*XrayListResponse, error)
	XrayManage(context.Context, *XrayManageRequest) (*GenericResponse, error)
	XraySetAutorun(context.Context, *XrayAutoRunRequest) (*GenericResponse, error)
	HookRestore(context.Context, *Empty) (*GenericResponse, error)
	mustEmbedUnimplementedVpnerManagerServer()
}

// UnimplementedVpnerManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVpnerManagerServer struct{}

func (UnimplementedVpnerManagerServer) UnblockList(context.Context, *Empty) (*UnblockListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnblockList not implemented")
}
func (UnimplementedVpnerManagerServer) UnblockAdd(context.Context, *UnblockAddRequest) (*GenericResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnblockAdd not implemented")
}
func (UnimplementedVpnerManagerServer) UnblockDel(context.Context, *UnblockDelRequest) (*GenericResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnblockDel not implemented")
}
func (UnimplementedVpnerManagerServer) InterfaceList(context.Context, *Empty) (*InterfaceListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InterfaceList not implemented")
}
func (UnimplementedVpnerManagerServer) InterfaceScan(context.Context, *Empty) (*InterfaceListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InterfaceScan not implemented")
}
func (UnimplementedVpnerManagerServer) InterfaceAdd(context.Context, *InterfaceActionRequest) (*GenericResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InterfaceAdd not implemented")
}
func (UnimplementedVpnerManagerServer) InterfaceDel(context.Context, *InterfaceActionRequest) (*GenericResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InterfaceDel not implemented")
}
func (UnimplementedVpnerManagerServer) DnsManage(context.Context, *ManageRequest) (*GenericResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DnsManage not implemented")
}
func (UnimplementedVpnerManagerServer) XrayCreate(context.Context, *XrayCreateRequest) (*GenericResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method XrayCreate not implemented")
}
func (UnimplementedVpnerManagerServer) XrayDelete(context.Context, *XrayRequest) (*GenericResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method XrayDelete not implemented")
}
func (UnimplementedVpnerManagerServer) XrayList(context.Context, *Empty) (*XrayListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method XrayList not implemented")
}
func (UnimplementedVpnerManagerServer) XrayManage(context.Context, *XrayManageRequest) (*GenericResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method XrayManage not implemented")
}
func (UnimplementedVpnerManagerServer) XraySetAutorun(context.Context, *XrayAutoRunRequest) (*GenericResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method XraySetAutorun not implemented")
}
func (UnimplementedVpnerManagerServer) HookRestore(context.Context, *Empty) (*GenericResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HookRestore not implemented")
}
func (UnimplementedVpnerManagerServer) mustEmbedUnimplementedVpnerManagerServer() {}
func (UnimplementedVpnerManagerServer) testEmbeddedByValue()                      {}

// UnsafeVpnerManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VpnerManagerServer will
// result in compilation errors.
type UnsafeVpnerManagerServer interface {
	mustEmbedUnimplementedVpnerManagerServer()
}

func RegisterVpnerManagerServer(s grpc.ServiceRegistrar, srv VpnerManagerServer) {
	// If the following call pancis, it indicates UnimplementedVpnerManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VpnerManager_ServiceDesc, srv)
}

func _VpnerManager_UnblockList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnerManagerServer).UnblockList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VpnerManager_UnblockList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnerManagerServer).UnblockList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VpnerManager_UnblockAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnblockAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnerManagerServer).UnblockAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VpnerManager_UnblockAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnerManagerServer).UnblockAdd(ctx, req.(*UnblockAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VpnerManager_UnblockDel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnblockDelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnerManagerServer).UnblockDel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VpnerManager_UnblockDel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnerManagerServer).UnblockDel(ctx, req.(*UnblockDelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VpnerManager_InterfaceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnerManagerServer).InterfaceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VpnerManager_InterfaceList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnerManagerServer).InterfaceList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VpnerManager_InterfaceScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnerManagerServer).InterfaceScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VpnerManager_InterfaceScan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnerManagerServer).InterfaceScan(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VpnerManager_InterfaceAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterfaceActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnerManagerServer).InterfaceAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VpnerManager_InterfaceAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnerManagerServer).InterfaceAdd(ctx, req.(*InterfaceActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VpnerManager_InterfaceDel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterfaceActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnerManagerServer).InterfaceDel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VpnerManager_InterfaceDel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnerManagerServer).InterfaceDel(ctx, req.(*InterfaceActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VpnerManager_DnsManage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnerManagerServer).DnsManage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VpnerManager_DnsManage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnerManagerServer).DnsManage(ctx, req.(*ManageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VpnerManager_XrayCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(XrayCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnerManagerServer).XrayCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VpnerManager_XrayCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnerManagerServer).XrayCreate(ctx, req.(*XrayCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VpnerManager_XrayDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(XrayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnerManagerServer).XrayDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VpnerManager_XrayDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnerManagerServer).XrayDelete(ctx, req.(*XrayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VpnerManager_XrayList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnerManagerServer).XrayList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VpnerManager_XrayList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnerManagerServer).XrayList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VpnerManager_XrayManage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(XrayManageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnerManagerServer).XrayManage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VpnerManager_XrayManage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnerManagerServer).XrayManage(ctx, req.(*XrayManageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VpnerManager_XraySetAutorun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(XrayAutoRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnerManagerServer).XraySetAutorun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VpnerManager_XraySetAutorun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnerManagerServer).XraySetAutorun(ctx, req.(*XrayAutoRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VpnerManager_HookRestore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VpnerManagerServer).HookRestore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VpnerManager_HookRestore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VpnerManagerServer).HookRestore(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// VpnerManager_ServiceDesc is the grpc.ServiceDesc for VpnerManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VpnerManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vpner.VpnerManager",
	HandlerType: (*VpnerManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UnblockList",
			Handler:    _VpnerManager_UnblockList_Handler,
		},
		{
			MethodName: "UnblockAdd",
			Handler:    _VpnerManager_UnblockAdd_Handler,
		},
		{
			MethodName: "UnblockDel",
			Handler:    _VpnerManager_UnblockDel_Handler,
		},
		{
			MethodName: "InterfaceList",
			Handler:    _VpnerManager_InterfaceList_Handler,
		},
		{
			MethodName: "InterfaceScan",
			Handler:    _VpnerManager_InterfaceScan_Handler,
		},
		{
			MethodName: "InterfaceAdd",
			Handler:    _VpnerManager_InterfaceAdd_Handler,
		},
		{
			MethodName: "InterfaceDel",
			Handler:    _VpnerManager_InterfaceDel_Handler,
		},
		{
			MethodName: "DnsManage",
			Handler:    _VpnerManager_DnsManage_Handler,
		},
		{
			MethodName: "XrayCreate",
			Handler:    _VpnerManager_XrayCreate_Handler,
		},
		{
			MethodName: "XrayDelete",
			Handler:    _VpnerManager_XrayDelete_Handler,
		},
		{
			MethodName: "XrayList",
			Handler:    _VpnerManager_XrayList_Handler,
		},
		{
			MethodName: "XrayManage",
			Handler:    _VpnerManager_XrayManage_Handler,
		},
		{
			MethodName: "XraySetAutorun",
			Handler:    _VpnerManager_XraySetAutorun_Handler,
		},
		{
			MethodName: "HookRestore",
			Handler:    _VpnerManager_HookRestore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vpner.proto",
}
