// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: vpner.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_vpner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_vpner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_vpner_proto_rawDescGZIP(), []int{0}
}

type GenericResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*GenericResponse_Success
	//	*GenericResponse_Error
	Result        isGenericResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericResponse) Reset() {
	*x = GenericResponse{}
	mi := &file_vpner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericResponse) ProtoMessage() {}

func (x *GenericResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vpner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericResponse.ProtoReflect.Descriptor instead.
func (*GenericResponse) Descriptor() ([]byte, []int) {
	return file_vpner_proto_rawDescGZIP(), []int{1}
}

func (x *GenericResponse) GetResult() isGenericResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GenericResponse) GetSuccess() *Success {
	if x != nil {
		if x, ok := x.Result.(*GenericResponse_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *GenericResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*GenericResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isGenericResponse_Result interface {
	isGenericResponse_Result()
}

type GenericResponse_Success struct {
	Success *Success `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type GenericResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GenericResponse_Success) isGenericResponse_Result() {}

func (*GenericResponse_Error) isGenericResponse_Result() {}

type Success struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Success) Reset() {
	*x = Success{}
	mi := &file_vpner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Success) ProtoMessage() {}

func (x *Success) ProtoReflect() protoreflect.Message {
	mi := &file_vpner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Success.ProtoReflect.Descriptor instead.
func (*Success) Descriptor() ([]byte, []int) {
	return file_vpner_proto_rawDescGZIP(), []int{2}
}

func (x *Success) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_vpner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_vpner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_vpner_proto_rawDescGZIP(), []int{3}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnblockListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*UnblockInfo         `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockListResponse) Reset() {
	*x = UnblockListResponse{}
	mi := &file_vpner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockListResponse) ProtoMessage() {}

func (x *UnblockListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vpner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockListResponse.ProtoReflect.Descriptor instead.
func (*UnblockListResponse) Descriptor() ([]byte, []int) {
	return file_vpner_proto_rawDescGZIP(), []int{4}
}

func (x *UnblockListResponse) GetRules() []*UnblockInfo {
	if x != nil {
		return x.Rules
	}
	return nil
}

type UnblockAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	ChainName     string                 `protobuf:"bytes,2,opt,name=chain_name,json=chainName,proto3" json:"chain_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockAddRequest) Reset() {
	*x = UnblockAddRequest{}
	mi := &file_vpner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockAddRequest) ProtoMessage() {}

func (x *UnblockAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vpner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockAddRequest.ProtoReflect.Descriptor instead.
func (*UnblockAddRequest) Descriptor() ([]byte, []int) {
	return file_vpner_proto_rawDescGZIP(), []int{5}
}

func (x *UnblockAddRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *UnblockAddRequest) GetChainName() string {
	if x != nil {
		return x.ChainName
	}
	return ""
}

type UnblockDelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockDelRequest) Reset() {
	*x = UnblockDelRequest{}
	mi := &file_vpner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockDelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockDelRequest) ProtoMessage() {}

func (x *UnblockDelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vpner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockDelRequest.ProtoReflect.Descriptor instead.
func (*UnblockDelRequest) Descriptor() ([]byte, []int) {
	return file_vpner_proto_rawDescGZIP(), []int{6}
}

func (x *UnblockDelRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type InterfaceListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interfaces    []*InterfaceInfo       `protobuf:"bytes,1,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfaceListResponse) Reset() {
	*x = InterfaceListResponse{}
	mi := &file_vpner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceListResponse) ProtoMessage() {}

func (x *InterfaceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vpner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceListResponse.ProtoReflect.Descriptor instead.
func (*InterfaceListResponse) Descriptor() ([]byte, []int) {
	return file_vpner_proto_rawDescGZIP(), []int{7}
}

func (x *InterfaceListResponse) GetInterfaces() []*InterfaceInfo {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

type InterfaceActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfaceActionRequest) Reset() {
	*x = InterfaceActionRequest{}
	mi := &file_vpner_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceActionRequest) ProtoMessage() {}

func (x *InterfaceActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vpner_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceActionRequest.ProtoReflect.Descriptor instead.
func (*InterfaceActionRequest) Descriptor() ([]byte, []int) {
	return file_vpner_proto_rawDescGZIP(), []int{8}
}

func (x *InterfaceActionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ManageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Act           ManageAction           `protobuf:"varint,1,opt,name=act,proto3,enum=structures.ManageAction" json:"act,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManageRequest) Reset() {
	*x = ManageRequest{}
	mi := &file_vpner_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageRequest) ProtoMessage() {}

func (x *ManageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vpner_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManageRequest.ProtoReflect.Descriptor instead.
func (*ManageRequest) Descriptor() ([]byte, []int) {
	return file_vpner_proto_rawDescGZIP(), []int{9}
}

func (x *ManageRequest) GetAct() ManageAction {
	if x != nil {
		return x.Act
	}
	return ManageAction_START
}

type SSManageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Act           ManageAction           `protobuf:"varint,1,opt,name=act,proto3,enum=structures.ManageAction" json:"act,omitempty"`
	ChainName     string                 `protobuf:"bytes,2,opt,name=chain_name,json=chainName,proto3" json:"chain_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSManageRequest) Reset() {
	*x = SSManageRequest{}
	mi := &file_vpner_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSManageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSManageRequest) ProtoMessage() {}

func (x *SSManageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vpner_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSManageRequest.ProtoReflect.Descriptor instead.
func (*SSManageRequest) Descriptor() ([]byte, []int) {
	return file_vpner_proto_rawDescGZIP(), []int{10}
}

func (x *SSManageRequest) GetAct() ManageAction {
	if x != nil {
		return x.Act
	}
	return ManageAction_START
}

func (x *SSManageRequest) GetChainName() string {
	if x != nil {
		return x.ChainName
	}
	return ""
}

type SSDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainName     string                 `protobuf:"bytes,1,opt,name=chain_name,json=chainName,proto3" json:"chain_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSDeleteRequest) Reset() {
	*x = SSDeleteRequest{}
	mi := &file_vpner_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSDeleteRequest) ProtoMessage() {}

func (x *SSDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vpner_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSDeleteRequest.ProtoReflect.Descriptor instead.
func (*SSDeleteRequest) Descriptor() ([]byte, []int) {
	return file_vpner_proto_rawDescGZIP(), []int{11}
}

func (x *SSDeleteRequest) GetChainName() string {
	if x != nil {
		return x.ChainName
	}
	return ""
}

type SSCreateWithChainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ss            *SSInfo                `protobuf:"bytes,1,opt,name=ss,proto3" json:"ss,omitempty"`
	ChainName     string                 `protobuf:"bytes,2,opt,name=chain_name,json=chainName,proto3" json:"chain_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSCreateWithChainRequest) Reset() {
	*x = SSCreateWithChainRequest{}
	mi := &file_vpner_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSCreateWithChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSCreateWithChainRequest) ProtoMessage() {}

func (x *SSCreateWithChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vpner_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSCreateWithChainRequest.ProtoReflect.Descriptor instead.
func (*SSCreateWithChainRequest) Descriptor() ([]byte, []int) {
	return file_vpner_proto_rawDescGZIP(), []int{12}
}

func (x *SSCreateWithChainRequest) GetSs() *SSInfo {
	if x != nil {
		return x.Ss
	}
	return nil
}

func (x *SSCreateWithChainRequest) GetChainName() string {
	if x != nil {
		return x.ChainName
	}
	return ""
}

type SSListResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	List          []*SSCreateWithChainRequest `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSListResponse) Reset() {
	*x = SSListResponse{}
	mi := &file_vpner_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSListResponse) ProtoMessage() {}

func (x *SSListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vpner_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSListResponse.ProtoReflect.Descriptor instead.
func (*SSListResponse) Descriptor() ([]byte, []int) {
	return file_vpner_proto_rawDescGZIP(), []int{13}
}

func (x *SSListResponse) GetList() []*SSCreateWithChainRequest {
	if x != nil {
		return x.List
	}
	return nil
}

var File_vpner_proto protoreflect.FileDescriptor

const file_vpner_proto_rawDesc = "" +
	"\n" +
	"\vvpner.proto\x12\x05vpner\x1a\x10structures.proto\"\a\n" +
	"\x05Empty\"m\n" +
	"\x0fGenericResponse\x12*\n" +
	"\asuccess\x18\x01 \x01(\v2\x0e.vpner.SuccessH\x00R\asuccess\x12$\n" +
	"\x05error\x18\x02 \x01(\v2\f.vpner.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\"#\n" +
	"\aSuccess\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"!\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"D\n" +
	"\x13UnblockListResponse\x12-\n" +
	"\x05rules\x18\x01 \x03(\v2\x17.structures.UnblockInfoR\x05rules\"J\n" +
	"\x11UnblockAddRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x1d\n" +
	"\n" +
	"chain_name\x18\x02 \x01(\tR\tchainName\"+\n" +
	"\x11UnblockDelRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"R\n" +
	"\x15InterfaceListResponse\x129\n" +
	"\n" +
	"interfaces\x18\x01 \x03(\v2\x19.structures.InterfaceInfoR\n" +
	"interfaces\"(\n" +
	"\x16InterfaceActionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\";\n" +
	"\rManageRequest\x12*\n" +
	"\x03act\x18\x01 \x01(\x0e2\x18.structures.ManageActionR\x03act\"\\\n" +
	"\x0fSSManageRequest\x12*\n" +
	"\x03act\x18\x01 \x01(\x0e2\x18.structures.ManageActionR\x03act\x12\x1d\n" +
	"\n" +
	"chain_name\x18\x02 \x01(\tR\tchainName\"0\n" +
	"\x0fSSDeleteRequest\x12\x1d\n" +
	"\n" +
	"chain_name\x18\x01 \x01(\tR\tchainName\"]\n" +
	"\x18SSCreateWithChainRequest\x12\"\n" +
	"\x02ss\x18\x01 \x01(\v2\x12.structures.SSInfoR\x02ss\x12\x1d\n" +
	"\n" +
	"chain_name\x18\x02 \x01(\tR\tchainName\"E\n" +
	"\x0eSSListResponse\x123\n" +
	"\x04list\x18\x01 \x03(\v2\x1f.vpner.SSCreateWithChainRequestR\x04list2\xe9\x05\n" +
	"\fVpnerManager\x127\n" +
	"\vUnblockList\x12\f.vpner.Empty\x1a\x1a.vpner.UnblockListResponse\x12>\n" +
	"\n" +
	"UnblockAdd\x12\x18.vpner.UnblockAddRequest\x1a\x16.vpner.GenericResponse\x12>\n" +
	"\n" +
	"UnblockDel\x12\x18.vpner.UnblockDelRequest\x1a\x16.vpner.GenericResponse\x12;\n" +
	"\rInterfaceList\x12\f.vpner.Empty\x1a\x1c.vpner.InterfaceListResponse\x12;\n" +
	"\rInterfaceScan\x12\f.vpner.Empty\x1a\x1c.vpner.InterfaceListResponse\x12E\n" +
	"\fInterfaceAdd\x12\x1d.vpner.InterfaceActionRequest\x1a\x16.vpner.GenericResponse\x12E\n" +
	"\fInterfaceDel\x12\x1d.vpner.InterfaceActionRequest\x1a\x16.vpner.GenericResponse\x129\n" +
	"\tDnsManage\x12\x14.vpner.ManageRequest\x1a\x16.vpner.GenericResponse\x126\n" +
	"\bSSCreate\x12\x12.structures.SSInfo\x1a\x16.vpner.GenericResponse\x12:\n" +
	"\bSSDelete\x12\x16.vpner.SSDeleteRequest\x1a\x16.vpner.GenericResponse\x12-\n" +
	"\x06SSList\x12\f.vpner.Empty\x1a\x15.vpner.SSListResponse\x12:\n" +
	"\bSSManage\x12\x16.vpner.SSManageRequest\x1a\x16.vpner.GenericResponseB,Z*github.com/ApostolDmitry/vpner/proto;protob\x06proto3"

var (
	file_vpner_proto_rawDescOnce sync.Once
	file_vpner_proto_rawDescData []byte
)

func file_vpner_proto_rawDescGZIP() []byte {
	file_vpner_proto_rawDescOnce.Do(func() {
		file_vpner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vpner_proto_rawDesc), len(file_vpner_proto_rawDesc)))
	})
	return file_vpner_proto_rawDescData
}

var file_vpner_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_vpner_proto_goTypes = []any{
	(*Empty)(nil),                    // 0: vpner.Empty
	(*GenericResponse)(nil),          // 1: vpner.GenericResponse
	(*Success)(nil),                  // 2: vpner.Success
	(*Error)(nil),                    // 3: vpner.Error
	(*UnblockListResponse)(nil),      // 4: vpner.UnblockListResponse
	(*UnblockAddRequest)(nil),        // 5: vpner.UnblockAddRequest
	(*UnblockDelRequest)(nil),        // 6: vpner.UnblockDelRequest
	(*InterfaceListResponse)(nil),    // 7: vpner.InterfaceListResponse
	(*InterfaceActionRequest)(nil),   // 8: vpner.InterfaceActionRequest
	(*ManageRequest)(nil),            // 9: vpner.ManageRequest
	(*SSManageRequest)(nil),          // 10: vpner.SSManageRequest
	(*SSDeleteRequest)(nil),          // 11: vpner.SSDeleteRequest
	(*SSCreateWithChainRequest)(nil), // 12: vpner.SSCreateWithChainRequest
	(*SSListResponse)(nil),           // 13: vpner.SSListResponse
	(*UnblockInfo)(nil),              // 14: structures.UnblockInfo
	(*InterfaceInfo)(nil),            // 15: structures.InterfaceInfo
	(ManageAction)(0),                // 16: structures.ManageAction
	(*SSInfo)(nil),                   // 17: structures.SSInfo
}
var file_vpner_proto_depIdxs = []int32{
	2,  // 0: vpner.GenericResponse.success:type_name -> vpner.Success
	3,  // 1: vpner.GenericResponse.error:type_name -> vpner.Error
	14, // 2: vpner.UnblockListResponse.rules:type_name -> structures.UnblockInfo
	15, // 3: vpner.InterfaceListResponse.interfaces:type_name -> structures.InterfaceInfo
	16, // 4: vpner.ManageRequest.act:type_name -> structures.ManageAction
	16, // 5: vpner.SSManageRequest.act:type_name -> structures.ManageAction
	17, // 6: vpner.SSCreateWithChainRequest.ss:type_name -> structures.SSInfo
	12, // 7: vpner.SSListResponse.list:type_name -> vpner.SSCreateWithChainRequest
	0,  // 8: vpner.VpnerManager.UnblockList:input_type -> vpner.Empty
	5,  // 9: vpner.VpnerManager.UnblockAdd:input_type -> vpner.UnblockAddRequest
	6,  // 10: vpner.VpnerManager.UnblockDel:input_type -> vpner.UnblockDelRequest
	0,  // 11: vpner.VpnerManager.InterfaceList:input_type -> vpner.Empty
	0,  // 12: vpner.VpnerManager.InterfaceScan:input_type -> vpner.Empty
	8,  // 13: vpner.VpnerManager.InterfaceAdd:input_type -> vpner.InterfaceActionRequest
	8,  // 14: vpner.VpnerManager.InterfaceDel:input_type -> vpner.InterfaceActionRequest
	9,  // 15: vpner.VpnerManager.DnsManage:input_type -> vpner.ManageRequest
	17, // 16: vpner.VpnerManager.SSCreate:input_type -> structures.SSInfo
	11, // 17: vpner.VpnerManager.SSDelete:input_type -> vpner.SSDeleteRequest
	0,  // 18: vpner.VpnerManager.SSList:input_type -> vpner.Empty
	10, // 19: vpner.VpnerManager.SSManage:input_type -> vpner.SSManageRequest
	4,  // 20: vpner.VpnerManager.UnblockList:output_type -> vpner.UnblockListResponse
	1,  // 21: vpner.VpnerManager.UnblockAdd:output_type -> vpner.GenericResponse
	1,  // 22: vpner.VpnerManager.UnblockDel:output_type -> vpner.GenericResponse
	7,  // 23: vpner.VpnerManager.InterfaceList:output_type -> vpner.InterfaceListResponse
	7,  // 24: vpner.VpnerManager.InterfaceScan:output_type -> vpner.InterfaceListResponse
	1,  // 25: vpner.VpnerManager.InterfaceAdd:output_type -> vpner.GenericResponse
	1,  // 26: vpner.VpnerManager.InterfaceDel:output_type -> vpner.GenericResponse
	1,  // 27: vpner.VpnerManager.DnsManage:output_type -> vpner.GenericResponse
	1,  // 28: vpner.VpnerManager.SSCreate:output_type -> vpner.GenericResponse
	1,  // 29: vpner.VpnerManager.SSDelete:output_type -> vpner.GenericResponse
	13, // 30: vpner.VpnerManager.SSList:output_type -> vpner.SSListResponse
	1,  // 31: vpner.VpnerManager.SSManage:output_type -> vpner.GenericResponse
	20, // [20:32] is the sub-list for method output_type
	8,  // [8:20] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_vpner_proto_init() }
func file_vpner_proto_init() {
	if File_vpner_proto != nil {
		return
	}
	file_structures_proto_init()
	file_vpner_proto_msgTypes[1].OneofWrappers = []any{
		(*GenericResponse_Success)(nil),
		(*GenericResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vpner_proto_rawDesc), len(file_vpner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vpner_proto_goTypes,
		DependencyIndexes: file_vpner_proto_depIdxs,
		MessageInfos:      file_vpner_proto_msgTypes,
	}.Build()
	File_vpner_proto = out.File
	file_vpner_proto_goTypes = nil
	file_vpner_proto_depIdxs = nil
}
